hosts:
	@if [ "${r}" = "init" ] || [ "${r}" = "uninit" ] || [ "${r}" = "reinit" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to init/uninit/reinit hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to init/uninit/reinit hosts";\
			fi\
		else\
			echo "No actions to init/uninit/reinit hosts";\
		fi;\
	elif [ "${r}" = "prepare" ] || [ "${r}" = "format" ] || [ "${r}" = "clean" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to prepare/format/clean hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to prepare/format/clean hosts";\
			fi\
		else\
			echo "No actions to prepare/format/clean hosts";\
		fi;\
	elif [ "${r}" = "create" ] || [ "${r}" = "recreate" ] || [ "${r}" = "copy" ] || [ "${r}" = "delete" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to create/copy/delete hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to create/copy/delete hosts";\
			fi\
		else\
			echo "No actions to create/copy/delete hosts";\
		fi;\
	elif [ "${r}" = "bootstrap" ] || [ "${r}" = "start" ] || [ "${r}" = "stop" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to bootstrap/start/stop hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to bootstrap/start/stop hosts";\
			fi\
		else\
			echo "No actions to bootstrap/start/stop hosts";\
		fi;\
	elif [ "${r}" = "enable" ] || [ "${r}" = "disable" ] || [ "${r}" = "config" ] || [ "${r}" = "change" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to enable/disable/config/change hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to enable/disable/config/change hosts";\
			fi\
		else\
			echo "No actions to enable/disable/config/change hosts";\
		fi;\
	elif [ "${r}" = "upload" ] || [ "${r}" = "download" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to upload/download hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to upload/download hosts";\
			fi\
		else\
			echo "No actions to upload/download hosts";\
		fi;\
	elif [ "${r}" = "install" ] || [ "${r}" = "uninstall" ] || [ "${r}" = "deploy" ] || [ "${r}" = "destroy" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to install/uninstall/deploy/destroy hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to install/uninstall/deploy/destroy hosts";\
			fi\
		else\
			echo "No actions to install/uninstall/deploy/destroy hosts";\
		fi;\
	elif [ "${r}" = "setup" ] || [ "${r}" = "add" ] || [ "${r}" = "remove" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to add/setup/remove hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to add/setup/remove hosts";\
			fi\
		else\
			echo "No actions to add/setup/remove hosts";\
		fi;\
	elif [ "${r}" = "fetch" ] || [ "${r}" = "disfetch" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to fetch/disfetch hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to fetch/disfetch hosts";\
			fi\
		else\
			echo "No actions to fetch/disfetch hosts";\
		fi;\
	elif [ "${r}" = "upgrade" ] || [ "${r}" = "downgrade" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to upgrade/downgrade hosts";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-hosts.yml -e '{hosts_all: True}' --tags='${r}';\
			else\
				echo "No actions to upgrade/downgrade hosts";\
			fi\
		else\
			echo "No actions to upgrade/downgrade hosts";\
		fi;\
	else\
		echo "No actions to hosts role";\
		exit;\
	fi

