_design:
  data_path: "/opt/dataiku/design/data"
  port: 8081

_deployer:
  data_path: "/opt/dataiku/deployer/data"
  port: 8082

_api:
  data_path: "/opt/dataiku/api/data"
  port: 8083
  license: "changeme"

_automation:
  data_path: "/opt/dataiku/automation/data"
  port: 8084

_govern:
  data_path: "/opt/dataiku/govern/data"
  port: 8085
  pgsql:
    db_name: govern_testdb
    db_user: govern_user
    db_password: changeme

_fm:
  data_path: "/opt/dataiku/fm/data"
  port: 8087
  pgsql:
    db_name: fm_testdb
    db_user: fm_user
    db_password: changeme

