
- name: Define Fact for Dataiku Fleet Version
  set_fact:
    dss_fm_file_name: "dataiku-fm-{{ _dss.major_version }}.{{ _dss.minor_version }}.{{ _dss.patch_version }}"
    dss_version: "{{ _dss.major_version }}.{{ _dss.minor_version }}.{{ _dss.patch_version }}"

