- name: Create Directory for Dataiku DSS Govern Node
  file:
    path: "{{ govern.data_path }}"
    state: directory
    owner: "{{ dss.user }}"
    group: "{{ dss.group }}"
    mode: 0755
  register: create_data_dir
- debug: msg={{ create_data_dir }}
  when: print_debug == true


- name: Install Dataiku DSS Govern Node
  become_user: "{{ dss.user }}"
  shell: |
    dataiku-dss-{{ dss.major_version }}.{{ dss.minor_version }}.{{ dss.patch_version }}/installer.sh \
    -t govern -d {{ govern.data_path }} -p {{ govern.port }}
  register: install_dss_govern_node
  args:
    chdir: "{{ dss.base_path }}"
- debug: msg={{ install_dss_govern_node }}
  when: print_debug == true
  # -l LICENSE_FILE]


- name: Setup PostgreSQL Database Connection
  become_user: "{{ dss.user }}"
  lineinfile:
    dest: "{{ govern.data_path }}/config/dip.properties"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
    backrefs: "{{ item.backrefs }}"
  register: setup_pgsql_db_connection
  with_items:
    - { regexp: "^psql.jdbc.url=", line: "psql.jdbc.url=jdbc:postgresql://{{ groups['postgres'][0] }}:5432/{{ govern.pgsql.db_name }}", state: present, backrefs: no }
    - { regexp: "^psql.jdbc.user=", line: "psql.jdbc.user={{ govern.pgsql.db_user }}", state: present, backrefs: yes }
    - { regexp: "^psql.jdbc.password", line: "psql.jdbc.password={{ govern.pgsql.db_password }}", state: present, backrefs: yes }
- debug: msg={{ setup_pgsql_db_connection }}
  when: print_debug == true


- name: Issue Bootstrapping the Initial Configuration of Govern
  become_user: "{{ dss.user }}"
  shell: |
    bin/govern-admin init-db
  register: issue_initial_config
  args:
    chdir: "{{ govern.data_path }}"
- debug: msg={{ issue_initial_config }}
  when: print_debug == true


- name: Enable Startup Dataiku DSS Govern Node At Boot Time
  shell: |
    dataiku-dss-{{ dss.major_version }}.{{ dss.minor_version }}.{{ dss.patch_version }}/scripts/install/install-boot.sh {{ govern.data_path }} {{ dss.user }}
  register: enable_startup_dss_govern_node
  args:
    chdir: "{{ dss.base_path }}"
- debug: msg={{ enable_startup_dss_govern_node }}
  when: print_debug == true


- name: Enable and Start Systemd Service for Dataiku DSS Govern Node
  systemd:
    daemon_reload: yes
    name: dataiku
    enabled: yes
    state: started
  register: enable_govern_node_systemd_service
- debug: msg={{ enable_govern_node_systemd_service }}
  when: print_debug == true

