#- name: Stop Dataiku DSS Govern Node Manually
#  shell: |
#    bin/dss stop
#  register: stop_dss_govern_node
#  ignore_errors: true
#  args:
#    chdir: "{{ govern.data_path }}"
#- debug: msg={{ stop_dss_govern_node }}
#  when: print_debug == true


- name: Disable and Stop Systemd Service for Dataiku DSS Govern Node
  become: true
  systemd:
    daemon_reload: yes
    name: dataiku
    enabled: no
    state: stopped
  register: disable_govern_node_systemd_service
  ignore_errors: true
- debug: msg={{ disable_govern_node_systemd_service }}
  when: print_debug == true


- name: Delete Directory for Dataiku DSS Govern Node
  become: true
  file:
    path: "{{ govern.data_path }}"
    state: absent
  register: delete_data_dir
  ignore_errors: true
- debug: msg={{ delete_data_dir }}
  when: print_debug == true


