---
- name: Check if DSS Tarball File Already Exists
  stat: path={{ _dss.base_path }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }}
  register: check_dss_tarball
- debug: msg={{ check_dss_tarball }}


- name: Check if DSS Installation Directory Already Exist
  stat: path={{ _dss.base_path }}/{{ dss_fm_file_name }}
  register: check_dss_install_dir


- name: Sanity Check for Existence of "{{ _dss.base_path }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }}" File or "{{ _dss.base_path }}/{{ dss_fm_file_name }}" Directory
  debug: msg="Both {{ _dss.base_path }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }} file and {{ _dss.base_path }}/{{ dss_fm_file_name }} Directory Already Exists"
  changed_when: check_dss_tarball.stat.exists == True and check_dss_install_dir.stat.exists == True


- name: Copy DSS Tarball from Local Directory, roles/dss/files
  copy: src={{ dss_fm_file_name }}.{{ _dss.bin_type }} dest={{ _dss.base_path }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }} mode=0644 owner={{ _dss.user }} group={{ _dss.group }}
  register: local_copy_dss
  when: _dss.download == false and check_dss_tarball.stat.exists != True


- name: Download DSS Software Binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: "{{ _dss.download_fm_url }}/{{ dss_version }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }}",
        dest: "{{ _dss.base_path }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }}" }
  when: _dss.download == true and check_dss_tarball.stat.exists != True


- name: Unarchive DSS tarball
  unarchive:
    src: "{{ _dss.base_path }}/{{ dss_fm_file_name }}.{{ _dss.bin_type }}"
    dest: "{{ _dss.base_path }}"
    #  /{{ dss_fm_file_name }}"
    owner: "{{ _dss.user }}"
    group: "{{ _dss.group }}"
    mode: "0755"
    remote_src: yes
  register: unarchive_dss_tarball
  when: check_dss_install_dir.stat.exists == false

