# CREATE USER <govern_user> WITH ENCRYPTED PASSWORD '<govern_pwd>';
# CREATE DATABASE <govern_db> OWNER <govern_user>;
# Where <govern_user>, <govern_pwd> and <govern_db> are the values of your choice.

- name: Install Psycopg2-binary Pip module
  become_user: postgres
  shell: |
    pip install psycopg2-binary
  register: install_psycopg2_pip_module


- name: Create the Database Specified in vars
  become_user: postgres
  postgresql_db: name={{ govern.pgsql.db_name }}
       template='template0'
       state=present
       login_unix_socket=/tmp
  register: database_created
  vars:
    ansible_python_interpreter: "/usr/bin/python3"


- name: Ensure User has access to the New Database
  become_user: postgres
  postgresql_user: db={{ govern.pgsql.db_name }}
       name={{ govern.pgsql.db_user }}
       password={{ govern.pgsql.db_password }}
       priv=ALL
       state=present
       login_unix_socket=/tmp
  register: user_created
  vars:
    ansible_python_interpreter: "/usr/bin/python3"


- name: Ensure User does not Have Unnecessary Permissions
  become_user: postgres
  postgresql_user: name={{ govern.pgsql.db_user }}
       role_attr_flags=SUPERUSER,CREATEDB,CREATEROLE,INHERIT,LOGIN,REPLICATION
       state=present
       login_unix_socket=/tmp
  register: permission_enrolled
  vars:
    ansible_python_interpreter: "/usr/bin/python3"


# role_attr_flags=NOSUPERUSER,NOCREATEDB
# role_attr_flags
# [NO]SUPERUSER
# [NO]CREATEROLE
# [NO]CREATEDB
# [NO]INHERIT
# [NO]LOGIN
# [NO]REPLICATION
# [NO]BYPASSRLS
# https://docs.ansible.com/ansible/2.8/modules/postgresql_user_module.html

