---
# Install Single VMWare Postgres
#
# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'

#
- name: Set facts for package name and list and network range
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall

#
- name: Enable firewall
  import_tasks: enable-firewall.yml
  tags: install

#
- name: Install Common Prerequisties and VMware Postgres RPM Packages For Single Instance
  import_tasks: install-pkgs.yml
  tags: install

#
- name: Initialize VMware Postgres Instance
  import_tasks: initialize-postgres.yml
  tags: install

#
- name: Enable SSL for Single VMware Postgres
  import_tasks: enable-ssl.yml
  tags: install
  when: enable_ssl == true

#
- name: Check the status of Single VMware Postgres
  import_tasks: check-status.yml
  tags: install

#
- name: Uninstall RPM Packages for Single VMware Postgres
  import_tasks: uninstall.yml
  tags: uninstall

#
- name: Upgrade RPM Packages for Single VMware Postgres
  import_tasks: upgrade.yml
  tags: upgrade
